[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
optimizer = true
optimizer_runs = 200
show_progress = true

[fuzz]
runs = 1024
max_test_rejects = 524288
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
